nodes:
  node1: 192.168.0.2:4000
  node2: 192.168.0.3:4000
vaultIndex:
  path: ./data
logFile:
  path: ./logfile
plugin:
  path: ./plugin
start_address: 127.0.0.1
port: 8080
save_location:
  vault_data: "./data"
  did_document: "./document" 
  publicKey: "./key"